### ISSUE TITLE
Passwordless login to Bridges 

### ISSUE THREAD

**Issue by daipayans** [radical-collaboration/MDFF-EnTK#1]
Hello, 
I am trying to setup gsissh for passwordless login to bridges. The inststructions provided in the README and what I have found online is based for Ubuntu systems. 

As I don't have a Ubuntu system, I have attempted installing gsissh in two other operating systems, Centos 7 and macOS Sierra v 10.12.6. However, I have not been succeful towards this effort.

Prior steps worked fine. The entk-version is 0.7.16

Any help/suggestion is greatly appreciated. 

Thanks,
Daipayan

**Comment by mturilli** [comment]
Hi Daipayan, we will need more details about the problem(s) you encountered when installing gsissh. I would recommend to use Centos 7, if that is the only available Linux distribution. Did you try to install the `gsi-openssh-clients` rpm package?

**Comment by mturilli** [comment]
From your email outside this ticket:

> I did have access to the Ubuntu system but have lost access. Can you provide me with the access again by resetting the password? 

Can you give me the fqdn/ip of that machine? 

> I had similar problems there. So, I am sure that I am missing something here. Please, include the instructions for paswordless login to Bridges. 

I need more details about the problem(s) you encountered.

> Also, help me understand why ssh won't work here? As per login instructions to Bridges it says either ssh or gsissh (https://www.psc.edu/bridges/user-guide/connecting-to-bridges#gsissh)

ssh on bridges works only with XSEDE for DUO Multi-Factor Authentication (MFA). MFA cannot be automated and therefore used by RCT in your place.

**Comment by lee212** [comment]
This can be closed, I suppose. @daipayans ?
