### ISSUE TITLE
TCL scripts verification for VMD with EnTK on HPC

### ISSUE THREAD

**Issue by lee212** [radical-collaboration/MDFF-EnTK#10]
The following items will be verified
- [x] vmd module load, instead of local installation (only on XSEDE Bridges)
- [x] specific vmd parameter options `-dispdev text -e`
- [x] code walkthrough confirming TCL scripts and its behavior, e.g. initial correct pdb without missing it between stages
- [x] simulation only, analysis stages are suppressed 
- [x] updates on tcl script in EnTK pipelines

These are identified during the discussion with Daipayan

**Comment by lee212** [comment]
[namd.stdout.txt](https://github.com/radical-collaboration/MDFF-Error/files/4251127/namd.stdout.txt)

**Comment by lee212** [comment]
[vmd.analysis.stdout.txt](https://github.com/radical-collaboration/MDFF-Error/files/4251757/vmd.analysis.stdout.txt)
[eighth_stage.tcl.txt](https://github.com/radical-collaboration/MDFF-Error/files/4251758/eighth_stage.tcl.txt)

Failed analysis after namd completion

The last stage contains:
```
total 3610
-rw-r--r--  1 hrlee mc3bggp  263989 Feb 25 14:19 4ake-target_autopsf.pdb
-rw-r--r--  1 hrlee mc3bggp  789906 Feb 25 14:19 1ake-initial_autopsf.psf
drwxr-xr-x 11 hrlee mc3bggp   34304 Feb 25 14:19 ..
-rwxr--r--  1 hrlee mc3bggp    1827 Feb 25 14:19 unit.000007.sh
-rw-r--r--  1 hrlee mc3bggp    2467 Feb 25 14:19 STDOUT
-rw-r--r--  1 hrlee mc3bggp       0 Feb 25 14:19 STDERR
-rw-r--r--  1 hrlee mc3bggp     314 Feb 25 14:19 eighth_stage.tcl
-rw-r--r--  1 hrlee mc3bggp 2006076 Feb 25 14:19 adk-step1.dcd
drwxr-xr-x  2 hrlee mc3bggp   26112 Feb 25 14:19 .
-rw-r--r--  1 hrlee mc3bggp     570 Feb 25 14:19 unit.000007.prof
```

**Comment by lee212** [comment]
[vmd.analysis.stdout.8th.txt](https://github.com/radical-collaboration/MDFF-Error/files/4252284/vmd.analysis.stdout.8th.txt)
[vmd.analysis.stdout.9th.txt](https://github.com/radical-collaboration/MDFF-Error/files/4252285/vmd.analysis.stdout.9th.txt)

**Comment by daipayans** [comment]
@lee212 NAMD is running fine...so simulation stage is now working. i have to check the analysis looks like it's running but the output should be different. NAMD-Entk protocol (simulation -> analysis) one cycle seems to be working. 

Accuracy of result depends on further refinement.

**Comment by lee212** [comment]
TODO items are completed, I think this can be closed.
