### ISSUE TITLE
Instructions to launch the MDFF workflow for project BIP115 on Summit

### ISSUE THREAD

**Issue by benjha** [radical-collaboration/MDFF-EnTK#13]
@daipayans 

Instructions for BIP115 project on Summit:

1. Go to ```/gpfs/alpine/world-shared/bip115``` directory

2. Activate enTK's python environment:

```$source ./activate_radical_env.sh```

3.  Go to ```/gpfs/alpine/world-shared/bip115/enTK_tests/mdff``` and launch the script:

```(radical_tools_python)$ python simple_mdff.summit.py --resource ornl_summit```

**Comment by daipayans** [comment]
@benjha Many thanks! Will test over the weekend.

**Comment by lee212** [comment]
@daipayans , just checking in if there is an issue on this. BTW, do you have an account on Summit and allocation? I am not certain if you can launch without it.

**Comment by lee212** [comment]
@daipayans , just checking in to see if you have a test run on Summit. I am also trying to have a scaling test on my end as well.

**Comment by mturilli** [comment]
@daipayans, @benjha any news about this ticket? If we do not hear from you I am afraid we will have to close this ticket.

**Comment by benjha** [comment]
Hi @mturilli 
These instructions does work. We are waiting Daipayan to verify if the output of the workflow is correct. If it isn't we could open another ticket.

**Comment by mturilli** [comment]
Thanks, I will close this then.
