### ISSUE TITLE
Taking node counts as a parameter on command line like `python simple_mdff.py --nodes 2`

### ISSUE THREAD

**Issue by lee212** [radical-collaboration/MDFF-EnTK#15]
This might be convenient for a scaling test and if a user specifies the number of nodes to start a job, it will override the defined value in the `resource_cfg.yml`

**Comment by mturilli** [comment]
Discussing whether this could be done by parsing the arguments in `simple_mdff.py` (e.g., using argparse). The idea is that this is an application choice, in this case `simple_mdff.py`. If the number of argument to parse is limited, an efficient way is to use `sys.argv` and a positional approach to command arguments.

**Comment by lee212** [comment]
@benjha, This has been updated and you may want to try in your terminal. Let us know if it shows different behavior than what you expected.

**Comment by lee212** [comment]
@benjha, I will close this for now but welcome to re-open if you don't see this is working.
