### ISSUE TITLE
Performance characterization with session profiling data

### ISSUE THREAD

**Issue by lee212** [radical-collaboration/MDFF-EnTK#20]
Here is a quick guide on how to collect profiling data for further analysis. EnTK is equipped with [radical.analytics](https://github.com/radical-cybertools/radical.analytics/) to measure performance data and it is enabled by:

Set env variables
-------------------

```
export RADICAL_PILOT_PROFILE=True
export RADICAL_ENTK_PROFILE=True
```

Environment variables are only active while ssh is alive. E.g. opening a new terminal requires to set these variables again.

Run entk script
-----------------

It is the same as before, run the script on a shell without changes e.g.:
```
python simple_mdff.py
```

Save session data (client)
----------------------------

Once the job is finished, a subdirectory is generated with a unique session name. This time, however, additional profiling files are saved (`*.prof`) in the directory to provide information such as when a job is queued, started, and terminated with a timestamp. We do NOT want to remove this session data but keep for future analysis.

Compress and share data
----------------------------

```
export SESSION_ID=<type your session id here>
tar czf ${SESSION_ID}.tar.gz $SESSION_ID
```

Tar the session data with its unique name and share it on the github repository. The SESSION_ID has a format like `re.session.<hostname>.$USER.<time>.<index>` e.g. `re.session.js-17-185.jetstream-cloud.org.hrlee.018485.0001`.

Upload to github repository
--------------------------------

It is convenient to upload the tar file to the github repository to share as long as it is under 50MB. There is a dedicated directory, `sessions` so move the tar file to there on the `MDFF-EnTK` repository. 

```
mv ${SESSION_ID}.tar.gz ./sessions
git add sessions/${SESSION_ID}.tar.gz
git commit -am "adding session ${SESSION_ID}"
git push
```

Data analysis
--------------

Now I can use `radical.analytics` to provide performance data such as scalability, time to completion, overhead, and resource utilization in a text and a PNG/PDF graphics format.

**Comment by lee212** [comment]
@daipayans and others, please collect profiling data (by enabling env vars) when you run experiments. I can produce plots and other data based on your session data with profiling information.

**Comment by benjha** [comment]
@daipayans Let me know when the replica test at larger scale is ready, it will be good to compare the default EnTK  resource allocation  vs. the one delivered faster results:

https://github.com/radical-collaboration/MDFF-EnTK/issues/19

**Comment by lee212** [comment]
As I joined BIP115, I might be able to submit jobs for performance characterization.

**Comment by lee212** [comment]
Recent experiments were completed with profiling data , thus this guideline can be closed for now.
