### ISSUE TITLE
Status update and next steps

### ISSUE THREAD

**Issue by lee212** [radical-collaboration/MDFF-EnTK#3]
8/29/19 4PM - meeting for
- Current status
  - EnTK on Bridges Tested
- Simple MDFF (possibly ReMDFF)
  - In Progress
  - TCL or Python scripts
- Summit migration
 - environment setup
 - scalability

**Comment by lee212** [comment]
https://docs.google.com/presentation/d/1NBGQ0lUFiFK0OlcWs4IK5RWv2xQ0OnBezvi6vxc7OoI/edit?usp=sharing

**Comment by shantenujha** [comment]
@lee212 -- thanks. please update the slides linked above to reflect the slides sent around yesterday.

Also, if you can provide updates on performance / scale that would be good.

**Comment by lee212** [comment]
The slides have been updated including recent changes.

Daipayan said the system for simple MDFF is using 1 CPU, which is too small to represent with performance/scale but probably ReMDFF have a system big enough to show benchmark results at scale. Maybe we can discuss this during the call?
