### ISSUE TITLE
Week 8 action items

### ISSUE THREAD

**Issue by daipayans** [radical-collaboration/MDFF-EnTK#30]
Software:
- [x] Migrate MDFF/EnTK to XSEDE resource (Bridges2 -  preferably) @lee212 @mturilli 
- [x] Performance analysis for the set of science runs @lee212 

Science:
1.8 A - ADK
- [x] 16 ns x 1 replica 
- [x] 10 ps/replica/iteration x 100 replicas x 16 iterations (on summit)
  - [ ] ~~alt. 20 ps/replica/iteration x 50 replicas x 16 iterations (on bridges2)~~
- [x] 160 ps/replica/iteration x 100 replicas x 1 iteration (on summit)
  - [ ] ~~alt. 320 ps/replica/iteration x 50 replicas x 1 iteration (on bridges2)~~
- [x] 500 ps/replica/iteration x 32 replicas x 1 iteration 
- [ ] 31.25 ps/replica/iteration x 32 replicas x 16 iterations
   - [x] (Adjusted)  62.5 ps/replica/iteration x 16 replicas x 16 iterations
   - [x] (Adjusted)  125 ps/replica/iteration x 8 replicas x 16 iterations
   - [x] (Adjusted)  250 ps/replica/iteration x 4 replicas x 16 iterations
   - [x] (Adjusted)  1 ns/replica/iteration x 16 replicas x 1 iteration
   - [x] (Adjusted)  2 ns/replica/iteration x 8 replicas x 1 iteration
   - [x] (Adjusted)  4 ns/replica/iteration x 4 replicas x 1 iteration

- [ ] `Phase boundary` conventional MDFF and MDFF/EnTK at what resolution (start with 2.5 A) 

Dependence of protocol on system size:
CODH 1.8 A and 3.0 A 
- [ ] same test cases as ADK

**Comment by lee212** [comment]
Bridges2 will be available on Feb 11th

**Comment by lee212** [comment]
first result with 16ns x 1 replica: https://github.com/radical-collaboration/MDFF-EnTK/tree/master/experiments/bridges2/simple_mdff_vds_1_replica_1.8angstrom_1iter_16000k_numsteps/simple-mdff-replica-0/0.Calculating_the_cross-correlation_coefficient

**Comment by lee212** [comment]
Status update: there are two problems that I've had; queue time and `gsissh` authentication timeout.
32 replica with 12hr jobs waited about 16-20 hours, and this triggers `gsissh` authentication revalidation. Under XSEDE machines, we use `gsissh` for rp's access_schema, and it's used to provide enough time window once the first auth is verified. This prevents getting results for the set of experiments requiring 32 and 100 replicas.

**Comment by lee212** [comment]
Result for 500 ps/replica/iteration x 32 replicas x 1 iteration is added: https://github.com/radical-collaboration/MDFF-EnTK/tree/master/experiments/bridges2/simple_mdff_vds_32replica_1.8angstrom_1iter_500k_numsteps

and the ` 31.25 ps` has to be adjusted to `31.24` as to avoid `FATAL ERROR: number of steps must be a multiple of stepsPerCycle`

**Comment by lee212** [comment]
The first try on 32ps was finished, and only a few replicas were successful: https://github.com/radical-collaboration/MDFF-EnTK/tree/master/experiments/bridges2/simple_mdff_vds_32replica_1.8angstrom_16iter_32k_numsteps
Another job is submitted to see if it was temporal issue.

**Comment by lee212** [comment]
Note that 672 - 1008 node hours are projected on Bridges2, this is calculated by the remaining experiments with 12 hrs and 24 hrs wall hour requirements. In specific, 16 replicas * 12 hrs + 8 replicas * 12 hrs + 4 replicas * 12 hrs (in total of 336 hrs) and 24 hours (additional 672 hours).

**Comment by lee212** [comment]
-  10 ps/replica/iteration x 100 replicas x 16 iterations (on summit)
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_100_replicas_1.8angstrom_16iter_10ps

- 160 ps/replica/iteration x 100 replicas x 1 iteration (on summit)
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_100_replicas_1.8angstrom_1iter_160ps

-  (Adjusted) 62.5 ps/replica/iteration x 16 replicas x 16 iterations
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_16_replicas_1.8angstrom_16iter_62.5ps

-  (Adjusted) 125 ps/replica/iteration x 8 replicas x 16 iterations
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_8_replicas_1.8angstrom_16iter_125ps

-  (Adjusted) 250 ps/replica/iteration x 4 replicas x 16 iterations
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_4_replicas_1.8angstrom_16iter_250ps

-  (Adjusted) 1 ns/replica/iteration x 16 replicas x 1 iteration
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_16_replicas_1.8angstrom_1iter_1ns

-  (Adjusted) 2 ns/replica/iteration x 8 replicas x 1 iteration
    https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_8_replicas_1.8angstrom_1iter_2ns

- (Adjusted) 4 ns/replica/iteration x 4 replicas x 1 iteration
   https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_4_replicas_1.8angstrom_1iter_4ns

**Comment by daipayans** [comment]
Many thanks @lee212 . I will start reviewing individual cases and prepare results.

**Comment by daipayans** [comment]
@lee212 For our records and future discssions:

Summary for **bridges2** experiments:
`simple_mdff_vds_1replica_1.8angstrom_1iter_16000k_numsteps` - OK
`simple_mdff_vds_32replica_1.8angstrom_16iter_32k_numsteps` - OK (no directories for incomplete iteration tasks).
`simple_mdff_vds_32replica_1.8angstrom_1iter_500k_numsteps` - OK

Summary for **summit** experiments:
I cannot find the path to your summit experiements. Please check and let me know.

**Comment by lee212** [comment]
Additional experiments with 1.8A
- 64 replica - 16 iteration - 20 ps
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_64_replicas_1.8angstrom_16iter_20ps
- 32 replica - 16 iteration - 40 ps
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_32_replicas_1.8angstrom_16iter_40ps

**Comment by lee212** [comment]
Additional experiments with 3.0A

* 100 replicas - 16 iteration - 10 ps (3.0A)
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_100_replicas_3.0angstrom_16iter_10ps
*  64 replica - 16 iteration - 20 ps (3.0A)
  n/a
* 32 replica - 16 iteration - 40 ps (3.0A)
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_32_replicas_3.0angstrom_16iter_40ps
* 16 replica - 16 iteration - 80 ps (3.0A)
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_16_replicas_3.0angstrom_16iter_80ps
* 8 replica - 16 iteration - 160 ps (3.0A)
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_8_replicas_3.0angstrom_16iter_160ps
* 1 replica - 1 iteration - 1.6 ns (3.0A)
  https://github.com/radical-experiments/MDFF-EnTK/tree/main/experiments/summit/simple_mdff_vds_1_replica_3.0angstrom_1iter_1.6ns
